# Generated by Django 5.2.4 on 2025-07-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0002_multi_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferenceresult',
            name='solution_name',
            field=models.CharField(blank=True, help_text='솔루션 이름', max_length=255),
        ),
        migrations.AlterField(
            model_name='inferenceresult',
            name='llm_output',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='inferenceresult',
            name='system_prompt',
            field=models.TextField(blank=True),
        ),
    ]
